# Generated by Django 5.2.7 on 2025-10-06 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspaper',
            options={'ordering': ['-published_date']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='publishers',
            field=models.ManyToManyField(related_name='newspapers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspapers', to='agency.topic'),
        ),
        migrations.AlterField(
            model_name='redactor',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
